### ISSUE TITLE
feedback la feedback

### ISSUE THREAD

**Issue by mihailfox** [stefanaberenghia/FeedbackITutorDotNet#1]
Am creat un branch nou pt Lecția 1, ce se numește lectia-01

**Comment by stefanaberenghia** [comment]
> Am creat un branch nou pt Lecția 1, ce se numește lectia-01

hehe, super! Faci pull request in master cand termini? :)

**Comment by stefanaberenghia** [comment]
> Am creat un branch nou pt Lecția 1, ce se numește lectia-01

Da, am descoperit acum. Mersi :)

**Comment by stefanaberenghia** [comment]
am editat acum md-ul. Mersi ca mi-ai spus. Cand o sa mai fie teme noi (lectia + tema 2) sunt tot legate de calculator; le poti face pe acelasi repo (branch) , dar la lectiile viitoare sa faci te rog repo nou :)
